name: Java CI with Maven, tests and documentation generation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  
jobs:
  build:
    runs-on: windows-latest
    steps:
    - run: export DISPLAY=:0.0
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v2
      with:
        java-version: '14'
        distribution: 'adopt'  
 
    - uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: '8.0'
    - name: create database
      run: mysql -uroot -h127.0.0.1 < src/sql/createExpenseTrackerDB.sql
    - name: Compile 
      run: mvn clean compile
    - name: Create Datanucleus schema
      run: mvn datanucleus:schema-create
    - name: Launch the server in background mode 
      run: mvn jetty:run &
    - name: Test with Maven
      run: mvn test
    - name: Install doxygen
      run: sudo apt-get install -y doxygen
    - name: Install graphviz
      run: sudo apt-get install -y graphviz
    - name: Generate documentation
      run: mvn doxygen:report
    - name: Copy some information into docs folder
      run: mvn validate
    - name: Publish on Github Pages
      uses: crazy-max/ghaction-github-pages@v2.3.0
      with:
        build_dir: docs/doxygen/html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
